# Generated by Django 4.2.7 on 2024-02-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_crud_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRUD',
            new_name='User',
        ),
    ]
