# Generated by Django 4.2.7 on 2024-02-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_crud_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
